name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Criar arquivo .env a partir dos Secrets
        run: |
          echo "ENV=production" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_SSL=require" >> .env

      - name: Build and push Docker image
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build -t $DOCKER_USERNAME/segunda-entrega:latest .
          docker push $DOCKER_USERNAME/segunda-entrega:latest


      - name: Start server com timeout para teste
        run: |
          docker run --rm --env-file .env $DOCKER_USERNAME/segunda-entrega:latest sh -c "
            timeout 20s sh -c 'npm start & sleep 5'
          "
