name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push Docker image
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build -t $DOCKER_USERNAME/segunda-entrega:latest 

      - name: Criar arquivo .env a partir dos Secrets
        run: |
          echo "ENV=production" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_SSL=require" >> .env

      - name: Build Docker image
        run: docker build -t meu-app .

      - name: List build folder
        run: |
          docker run --rm meu-app ls -l /app/build

      - name: Start server with test and timeout
        run: |
            docker run --rm --env-file .env meu-app sh -c "
            timeout 20s sh -c 'npm start & sleep 5'
            "
